[phases.setup]
nixPkgs = ["libGL", "python39"]

[start]
cmd = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port $PORT"
